name: Skyline DataMiner Deploy Action
uses: SkylineCommunications/Skyline-DataMiner-Deploy-Action@v1.0.11
with:
api-key: ${{ secrets.DATAMINER_DEPLOY_KEY }}
solution-path: AutomationScript.sln
artifact-name: EmpowerHelloWorld
version: 1.0.1
timeout: # optional, default is 900
stage: # optional, default is All
artifact-id:
build-number: ${{ github.run_number }}
